### ISSUE TITLE
OrderPayments not loaded in DB with current seeds

### ISSUE THREAD

**Issue by nfilzi** [lewagon/rails-db-advanced-boilerplate#12]
```ruby
# db/seeds.rb:53
puts "[6/6] Parsing payments..."
order_payments = []

CSV.foreach('db/brazilian-ecommerce/olist_order_payments_dataset.csv', headers: true) do |row|
  order_payment = OrderPayment.new(row.to_hash)
  order_payment.order_id = order_ids_mapping[row["order_csv_id"]] <--- 🚨
  order_payments << order_payment
end
```

This `row["order_csv_id"]` will always return nil, as there is no `order_csv_id` in the `olist_order_payments_dataset.csv` file. 
We could fix it by referencing `row["order_id"]` instead.

The more important question though: **should this be fixed?** This part of the data is not used anywhere during the lecture.
Should we simply remove the whole `OrderPayment` logic to gain a little teacher time when it comes to seeding?

**Comment by nfilzi** [comment]
Attempt at bumping this issue @db0sch 🙏🏽

**Comment by dmilon** [comment]
Hi @nfilzi :wave: Thank you for your feedback :pray: Since the order payments data are not used in the lecture, I've removed these instructions from the seed file :ok_hand:
